import os


SQS_WAIT_TIME = os.getenv('SQS_WAIT_TIME', 20)
SLEEP_TIME = os.getenv('SLEEP_TIME', 20)
PROD_LOGGER = os.getenv('PROD_LOGGER', False)
SPOTIFY_CLIENT_ID = os.getenv('SPOTIFY_CLIENT_ID')
SPOTIFY_CLIENT_SECRET = os.getenv('SPOTIFY_CLIENT_SECRET')
ECHO_NEST_API_KEY = os.getenv('ECHO_NEST_API_KEY')
